### ISSUE TITLE
check_puppet.rb - option to disable process check

### ISSUE THREAD

**Issue by lbischof** [HariSekhon/nagios-plugins#107]
Hi,
We currently run Puppet with a nightly cronjob. I would really like to use check_puppet.rb, but I don't see an option to disable the process checking and just commenting out check_proc doesn't work. Thanks

**Comment by HariSekhon** [comment]
Hi @lbischof 

Did you try commenting out the check_proc call on line 330?

Could you clarify what you tried and what the error was?

I don't think it'd be much of a big deal to add a ```--no-process-check``` switch to prevent the check_proc call from running but it would help to check what you've tried first.

Thanks

Hari

**Comment by lbischof** [comment]
Yes, I removed line 330 and get the following error message:
```
/usr/lib64/nagios/plugins/custom/check_puppet.rb:341:in `+': no implicit conversion of NoMethodError into String (TypeError)
	from /usr/lib64/nagios/plugins/custom/check_puppet.rb:341:in `rescue in <main>'
	from /usr/lib64/nagios/plugins/custom/check_puppet.rb:337:in `<main>'
```

I also receive the following error regardless of the mentioned change (I'll open a new issue if you would like):
```
Could not retrieve fact='concat_basedir', resolution='<anonymous>': no implicit conversion of nil into String
```

**Comment by HariSekhon** [comment]
You might need to comment out line 320 as well.

**Comment by lbischof** [comment]
Thanks. Line 320 and removing it in: `for x in [` helped.
