### ISSUE TITLE
check_kafka.py kafkaProducer() Unrecognized configs: session_timeout_ms

### ISSUE THREAD

**Issue by Claxor** [HariSekhon/nagios-plugins#157]
Hello.

check_kafka.py appears to be passing a keyword argument to kafkaProducer() that is not defined as a class argument.

I commented it out locally and it started to work.

```
./check_kafka.py -H localhost:9092  --topic=healthcheck -t 30000 --debug
/usr/lib64/python2.6/site-packages/cryptography/__init__.py:26: DeprecationWarning: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of cryptography will drop support for Python 2.6
  DeprecationWarning
2017-05-04 11:39:02,587 - cli.py[main:162](1625) - DEBUG - enabling debug logging
2017-05-04 11:39:02,587 - cli.py[verbose:294](1625) - DEBUG - setting verbose to 3
2017-05-04 11:39:02,587 - cli.py[main:165](1625) - INFO  - Hari Sekhon check_kafka.py version 0.4.0 =>  CLI version 0.3 =>  Utils version 0.10.20
2017-05-04 11:39:02,587 - cli.py[main:166](1625) - INFO  - https://github.com/harisekhon/nagios-plugins
2017-05-04 11:39:02,587 - cli.py[main:167](1625) - INFO  - verbose level: 3 (DEBUG)
2017-05-04 11:39:02,587 - utils.py[log_option:2155](1625) - INFO  - timeout:  30000
2017-05-04 11:39:02,587 - cli.py[main:170](1625) - DEBUG - setting timeout alarm (30000)
2017-05-04 11:39:02,587 - utils.py[log_option:2155](1625) - INFO  - brokers:  localhost:9092
2017-05-04 11:39:02,588 - utils.py[log_option:2155](1625) - INFO  - topic:  healthcheck
2017-05-04 11:39:02,588 - utils.py[log_option:2155](1625) - INFO  - partition:  0
2017-05-04 11:39:02,588 - utils.py[log_option:2155](1625) - INFO  - acks:  1
2017-05-04 11:39:02,588 - threshold.py[__init__:50](1625) - DEBUG - warning threshold simple = upper
2017-05-04 11:39:02,588 - threshold.py[__init__:51](1625) - DEBUG - warning threshold positive = True
2017-05-04 11:39:02,588 - threshold.py[__init__:52](1625) - DEBUG - warning threshold integer = True
2017-05-04 11:39:02,588 - threshold.py[__init__:53](1625) - DEBUG - warning threshold min = None
2017-05-04 11:39:02,588 - threshold.py[__init__:54](1625) - DEBUG - warning threshold max = None
2017-05-04 11:39:02,588 - threshold.py[__parse_threshold__:72](1625) - DEBUG - warning threshold given = '1'
2017-05-04 11:39:02,589 - threshold.py[__parse_threshold__:106](1625) - DEBUG - warning threshold upper boundary = 1.0
2017-05-04 11:39:02,589 - threshold.py[__parse_threshold__:107](1625) - DEBUG - warning threshold lower boundary = None
2017-05-04 11:39:02,589 - utils.py[log_option:2155](1625) - INFO  - warning:  1
2017-05-04 11:39:02,589 - threshold.py[__init__:50](1625) - DEBUG - critical threshold simple = upper
2017-05-04 11:39:02,589 - threshold.py[__init__:51](1625) - DEBUG - critical threshold positive = True
2017-05-04 11:39:02,589 - threshold.py[__init__:52](1625) - DEBUG - critical threshold integer = True
2017-05-04 11:39:02,589 - threshold.py[__init__:53](1625) - DEBUG - critical threshold min = None
2017-05-04 11:39:02,589 - threshold.py[__init__:54](1625) - DEBUG - critical threshold max = None
2017-05-04 11:39:02,589 - threshold.py[__parse_threshold__:72](1625) - DEBUG - critical threshold given = '2'
2017-05-04 11:39:02,589 - threshold.py[__parse_threshold__:106](1625) - DEBUG - critical threshold upper boundary = 2.0
2017-05-04 11:39:02,590 - threshold.py[__parse_threshold__:107](1625) - DEBUG - critical threshold lower boundary = None
2017-05-04 11:39:02,590 - utils.py[log_option:2155](1625) - INFO  - critical:  2
2017-05-04 11:39:02,590 - pubsub_nagiosplugin.py[run:117](1625) - INFO  - subscribing
2017-05-04 11:39:02,708 - check_kafka.py[subscribe:223](1625) - DEBUG - partition assignments: set([])
2017-05-04 11:39:02,708 - check_kafka.py[subscribe:229](1625) - DEBUG - assigning partition 0 to consumer
2017-05-04 11:39:02,708 - check_kafka.py[subscribe:232](1625) - DEBUG - partition assignments: set([TopicPartition(topic='healthcheck', partition=0)])
2017-05-04 11:39:02,708 - check_kafka.py[subscribe:234](1625) - DEBUG - getting current offset
2017-05-04 11:39:02,734 - check_kafka.py[subscribe:242](1625) - DEBUG - recorded starting offset '4'
2017-05-04 11:39:02,734 - pubsub_nagiosplugin.py[run:119](1625) - INFO  - publishing message "Test message from Hari Sekhon check_kafka.py on host localhost at epoch 1493861942.59 (Thu May  4 11:39:02 2017) with random token '7IwOD1156V0sKLOAESO4'"
2017-05-04 11:39:02,734 - check_kafka.py[publish:246](1625) - DEBUG - creating producer
2017-05-04 11:39:02,734 - nagiosplugin.py[main:249](1625) - DEBUG - exception: 'AssertionError'
2017-05-04 11:39:02,735 - nagiosplugin.py[main:250](1625) - DEBUG - Traceback (most recent call last):
  File "/var/tmp/git/nagios-plugins/pylib/harisekhon/nagiosplugin/nagiosplugin.py", line 234, in main
    super(NagiosPlugin, self).main()
  File "/var/tmp/git/nagios-plugins/pylib/harisekhon/cli.py", line 179, in main
    self.run()
  File "./check_kafka.py", line 113, in run
    super(CheckKafka, self).run()
  File "/var/tmp/git/nagios-plugins/pylib/harisekhon/nagiosplugin/pubsub_nagiosplugin.py", line 121, in run
    self.publish()
  File "./check_kafka.py", line 254, in publish
    session_timeout_ms=self.timeout_ms,
  File "/usr/lib/python2.6/site-packages/kafka/producer/kafka.py", line 307, in __init__
    assert not configs, 'Unrecognized configs: %s' % configs
AssertionError: Unrecognized configs: {'session_timeout_ms': 14999500.0}

UNKNOWN: Nagios Plugin Exception: AssertionError: AssertionError: Unrecognized configs: {'session_timeout_ms': 14999500.0}. Please try latest version from https:/github.com/HariSekhon/nagios-plugins and if problem persists paste the full output using the --debug switch in to a ticket for a fix/update at https://github.com/HariSekhon/nagios-plugins/issues

Traceback (most recent call last):
  File "/var/tmp/git/nagios-plugins/pylib/harisekhon/nagiosplugin/nagiosplugin.py", line 234, in main
    super(NagiosPlugin, self).main()
  File "/var/tmp/git/nagios-plugins/pylib/harisekhon/cli.py", line 179, in main
    self.run()
  File "./check_kafka.py", line 113, in run
    super(CheckKafka, self).run()
  File "/var/tmp/git/nagios-plugins/pylib/harisekhon/nagiosplugin/pubsub_nagiosplugin.py", line 121, in run
    self.publish()
  File "./check_kafka.py", line 254, in publish
    session_timeout_ms=self.timeout_ms,
  File "/usr/lib/python2.6/site-packages/kafka/producer/kafka.py", line 307, in __init__
    assert not configs, 'Unrecognized configs: %s' % configs
AssertionError: Unrecognized configs: {'session_timeout_ms': 14999500.0}
```

**Comment by HariSekhon** [comment]
This is likely due to updating the plugin via `git pull` without updating the kafka library which requires that setting, so it was added in later versions.

The official procedure of `make update` would have done both a `git pull`, `git submodule update` and upgrade of any module dependencies, which should have avoided this issue.

**Comment by Claxor** [comment]
Hey hey.

We're talking about the same module as from here right?
http://kafka-python.readthedocs.io/en/master/apidoc/KafkaProducer.html

The class KafkaProducer, in the latest 1.3.3 version doesn't have the class parameter "session_timeout_ms"

Thanks for any clarification.

**Comment by HariSekhon** [comment]
@Claxor 

Sorry for the late reply this got lost in the shuffle, yes you're correct my system had been updating the other kafka library, I've updated the check to work with the latest library.

I've also made some improvements around randomizing partition selection if not specified and adding support for environment variables for convenience.

Cheers

Hari
