### ISSUE TITLE
ImportError: No module named _curses

### ISSUE THREAD

**Issue by axil76** [HariSekhon/nagios-plugins#186]
Hello,
I updated python to python 2.7 to run the check_kafka.py script, I got the following error message and I found nothing on the _curses module. can you tell me what to do

Traceback (most recent call last):
  File "./check_kafka.py", line 58, in <module>
    from harisekhon.utils import log, log_option, ERRORS, CriticalError, UnknownError
  File "/usr/lib/nagios/plugins/pylib/harisekhon/__init__.py", line 26, in <module>
    from harisekhon.cli import CLI
  File "/usr/lib/nagios/plugins/pylib/harisekhon/cli.py", line 42, in <module>
    import _curses
ImportError: No module named _curses

thank you

**Comment by HariSekhon** [comment]
Can you please try rebuilding the project by running

```make python```

since you probably don't have the PyPI modules installed in the new python version's site-packages.

**Comment by HariSekhon** [comment]
Did this manage to get it working after `make python`?
