### ISSUE TITLE
NRPE: Unable to read output check_yum.py

### ISSUE THREAD

**Issue by Yiejoon4** [HariSekhon/nagios-plugins#197]
Hi there,

I have an issue to read the output of the yum plugin. Here is the output of the debug(run as root):

/usr/lib/nagios/plugins/check_yum --all-updates --cache-only -vvv
Nagios Plugin for Yum updates on RedHat/CentOS systems - Version 0.8.7
Author: Hari Sekhon

setting plugin timeout to 30 seconds
running command: /usr/bin/yum check-update -C
Returncode: '0'
Output: 'Loaded plugins: product-id, search-disabled-repos, subscription-manager
'
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_yum", line 622, in <module>
    main()
  File "/usr/lib/nagios/plugins/check_yum", line 616, in main
    result, output = tester.test_yum_updates()
  File "/usr/lib/nagios/plugins/check_yum", line 427, in test_yum_updates
    return self.test_all_updates()
  File "/usr/lib/nagios/plugins/check_yum", line 438, in test_all_updates
    number_updates = self.get_all_updates()
  File "/usr/lib/nagios/plugins/check_yum", line 288, in get_all_updates
    output = self.run(cmd)
  File "/usr/lib/nagios/plugins/check_yum", line 186, in run
    self.check_returncode(returncode, output)
  File "/usr/lib/nagios/plugins/check_yum", line 197, in check_returncode
    if "You must run this command as root" in output[2]:
IndexError: list index out of range

Thanks.

**Comment by HariSekhon** [comment]
I've just pushed a fix which should correct this, please try again and let me know.

**Comment by Yiejoon4** [comment]
Looks good, thanks for bug fixing.
