### ISSUE TITLE
check_elasticsearch_x-pack_license_expiry.py  : Problem with 7.1 license ?

### ISSUE THREAD

**Issue by pantoufleCC** [HariSekhon/Nagios-Plugins#220]
Our new ELK instance is 7.1 version
, and X-Pack is configured with new default => **Basic** X-Pack licence .
( This kind of license is also available in 6.5+ ).

Error Message is:

UNKNOWN: KeyError: u'expiry_date_in_millis'. API may have changed. Please try latest version from https:/github.com/HariSekhon/nagios-plugins and if problem persists paste the full output using the --debug switch in to a ticket for a fix/update at https:/

**Comment by pantoufleCC** [comment]
I use container version .

did you need some trace or debug output ?

**Comment by pantoufleCC** [comment]
i found how to get more information:

Trace with -vvv

regards ;)

```

2019-05-27 12:09:28,966 - request_handler.py[req:63](29) - DEBUG - GET https://xxx-xxxxxx.xxx.xxx.xxxx.xxxxx:9200/_xpack/license?human=true
2019-05-27 12:09:28,998 - request_handler.py[log_output:120](29) - DEBUG - response: 200 OK
2019-05-27 12:09:28,998 - request_handler.py[log_output:121](29) - DEBUG - content:
================================================================================
{
  "license" : {
    "status" : "active",
    "uid" : "2a407b2c-f254-42b3-8f67-0759d6503888",
    "type" : "basic",
    "issue_date" : "2019-05-23T08:43:22.334Z",
    "issue_date_in_millis" : 1558601002334,
    "max_nodes" : 1000,
    "issued_to" : "xxx-yyyyyyyyyyyyy-zz",
    "issuer" : "elasticsearch",
    "start_date" : "1969-12-31T23:59:59.999Z",
    "start_date_in_millis" : -1
  }
}
================================================================================
2019-05-27 12:09:28,998 - rest_nagiosplugin.py[run:139](29) - INFO  - parsing json response
2019-05-27 12:09:28,998 - rest_nagiosplugin.py[process_json:177](29) - DEBUG - JSON prettified:

{
    "license": {
        "issue_date": "2019-05-23T08:43:22.334Z",
        "issue_date_in_millis": 1558601002334,
        "issued_to": "xxx-yyyyyyyyyyyyy-zz",
        "issuer": "elasticsearch",
        "max_nodes": 1000,
        "start_date": "1969-12-31T23:59:59.999Z",
        "start_date_in_millis": -1,
        "status": "active",
        "type": "basic",
        "uid": "2a407b2c-f254-42b3-8f67-0759d6503888"
    }
}
================================================================================
UNKNOWN: Traceback (most recent call last):
  File "/github/nagios-plugins/pylib/harisekhon/nagiosplugin/rest_nagiosplugin.py", line 178, in process_json
    return self.parse_json(self.json_data)
  File "./check_elasticsearch_x-pack_license_expiry.py", line 78, in parse_json
    expiry_millis = license_data['expiry_date_in_millis']
KeyError: u'expiry_date_in_millis'. API may have changed. Please try latest version from https:/github.com/HariSekhon/nagios-plugins and if problem persists paste the full output using the --debug switch in to a ticket for a fix/update at https://github.com/HariSekhon/nagios-plugins/issues

```

**Comment by pantoufleCC** [comment]
When license Type is "platinium", we get 2 informations who are missing if type = "basic"

```
    "expiry_date" : "2020-06-30T23:59:59.999Z",
    "expiry_date_in_millis" : 1593561599999,
```

**Comment by HariSekhon** [comment]
Thanks for raising this and for the debug info - it should be easy to fix in code.

I can't do this from my current work contract due to everything being locked out so will have to find some out of hours time to write a quick fix, may try tomorrow night after work if I get time.

**Comment by HariSekhon** [comment]
I've just pushed a fix to take in to account the newer basic license type and tested it on Elasticsearch 7.1.1.

Please give it a try and let me know.

I have also added a switch --basic, which you must specify to avoid warning that you are on a basic license.
