### ISSUE TITLE
check_cassandra_heap.fatpack.pl -  CRITICAL: error: neither username nor password can be blank

### ISSUE THREAD

**Issue by peter-snr** [HariSekhon/Nagios-Plugins#336]
Executing without username or password gives CRITICAL error.
E.G.
`./check_cassandra_heap.fatpack.pl -w 75 -c 90`
`CRITICAL: error: neither username nor password can be blank`

Usage specifies either can be optional.

```
usage: check_cassandra_heap.fatpack.pl [ options ]

-n  --nodetool    Path to 'nodetool' command if not in $PATH
                  (/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/local/cassandra/bin:/opt/cassandra/bin:/cassandra/bin)
-H  --host        Cassandra node         ($CASSANDRA_HOST, $HOST)
-P  --port        Cassandra JMX port     ($CASSANDRA_PORT, $PORT, default: 7199)
-u  --user        Cassandra JMX user     (optional, $CASSANDRA_USERNAME, $CASSANDRA_USER, $USERNAME, $USER)
-p  --password    Cassandra JMX password (optional, $CASSANDRA_PASSWORD, $PASSWORD)
```

Work around, specify username and password, can contain anything.
E.G.
```
[root@awsire-emea02-cassdb01 pg-wip]# ./check_cassandra_heap.fatpack.pl -u 'fred' -p 'pass'
OK: 43.43% heap used (3409.94/7850.69 MB) | 'heap_used_%'=43.43%;80;90; heap_used=3409.94MB heap_total=7850.69MB
```

**Comment by HariSekhon** [comment]
If they're defined then they can't be blank. It's probably picking up `$USER` from your environment and then wanting `$PASSWORD` / `--password`.

If you run it with `-v -v -v` it'll print debugging information.

**Comment by peter-snr** [comment]
```
#check_cassandra_heap.fatpack.pl -vvv -w 80 -c 90
 verbose mode on

check_cassandra_heap.pl version 0.2.2  =>  Hari Sekhon Utils version 1.19.6

nodetool:                 nodetool
port:                     7199
user:                     root
warning  upper:           80
critical upper:           90

setting timeout to 10 secs

fetching cluster node heap information
cmd: /bin/nodetool --port '7199' --username 'root' info
output:

error: neither username nor password can be blank
-- StackTrace --
java.lang.AssertionError: neither username nor password can be blank
        at org.apache.cassandra.tools.NodeProbe.<init>(NodeProbe.java:138)
        at org.apache.cassandra.tools.NodeProbeFactory.create(NodeProbeFactory.java:32)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.connect(NodeTool.java:343)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:281)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.accept(NodeTool.java:268)
        at org.apache.cassandra.tools.NodeTool$NodeToolCmd.accept(NodeTool.java:245)
        at org.apache.cassandra.tools.NodeTool.execute(NodeTool.java:182)
        at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:54)


exitcode: 2

CRITICAL: error: neither username nor password can be blank

# echo $USER
root
```

**Comment by HariSekhon** [comment]
Closing for lack of feedback.

You're welcome to re-open if needed.
