### ISSUE TITLE
Failing to build manually following the steps in the README

### ISSUE THREAD

**Issue by famfop** [HariSekhon/Nagios-Plugins#363]
I am currently trying to reproduce the steps for the manual build. I did
```
git clone https://github.com/harisekhon/nagios-plugins
cd nagios-plugins
git submodule init
git submodule update
```
followed by
```
sudo cpan $(sed 's/#.*//' setup/cpan-requirements*.txt lib/setup/cpan-requirements*.txt)
```
just to finally get an error when doing the following step
```
# sudo pip install -r requirements.txt -r pylib/requirements.txt
Collecting boto3==1.10.40 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/5d/62/9629ee1a41757b65b55c2070d2e0afee80a89e3ea0076b9b9669a773308b/boto3-1.10.40-py2.py3-none-any.whl
Collecting GitPython==2.1.15 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/7a/c9/6e1aec0893efe66f407d2e14a3daba73dbb39bbeeb72142b037c4a224d40/GitPython-2.1.15-py2.py3-none-any.whl
Collecting happybase==1.2.0 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/d1/9c/f5f7bdb5439cda2b7da4e20ac24ec0e2455fd68aade8397f211d2994c39d/happybase-1.2.0.tar.gz
Collecting humanize==0.5.1 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/8c/e0/e512e4ac6d091fc990bbe13f9e0378f34cf6eecd1c6c268c9e598dcf5bb9/humanize-0.5.1.tar.gz
Collecting kafka-python==1.4.7 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/49/c9/9863483a1353700ba87821b4f39085eb18fd1bcbb1e954c697177d67f03f/kafka_python-1.4.7-py2.py3-none-any.whl
Collecting mysqlclient==1.4.6 (from -r requirements.txt (line 21))
  Using cached https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    sh: 1: mysql_config: not found
    sh: 1: mariadb_config: not found
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-Hz6_kC/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    EnvironmentError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-Hz6_kC/mysqlclient/
```
I grep'ed the repository looking for an `egg_info` and found the comment lines 81-83 - I was not exactly sure how to proceed so I uncommented the following two lines 84,85 but this did reproduce the same error.

I did these steps on an almost "vanilla"-system (Debian GNU/Linux 10 with python-pip installed via apt-get). It seems some step is missing in the README - or I am too stupid. In any case I'd be happy to get a hint on how to fix this and get the build working.

**Comment by HariSekhon** [comment]
You are missing the `mysql_config` command locally.

Have you tried installing using `make`? That usually pulls in system packages and things you may need.
